Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace csharp_boolflix.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/MovieController.cs
using csharp_boolflix.Data.FormModels;
using csharp_boolflix.Models;
using csharp_boolflix.Models.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace csharp_boolflix.Controllers
{
    [Authorize]
    public class MovieController : Controller
    {
        DbMovieRepository dbMovieRepository;
        DbCategoryRepository dbCategoryRepository;
        DbActorRepository dbActorRepository;
        public MovieController(DbMovieRepository _dbMovieRepository, DbCategoryRepository _dbCategoryRepository, DbActorRepository _dbActorRepository)
        {
            dbMovieRepository = _dbMovieRepository;
            dbCategoryRepository = _dbCategoryRepository;
            dbActorRepository = _dbActorRepository;
        }
        public IActionResult Index()
        {
            List<Movie> movies = dbMovieRepository.GetAll(false, false);
            return View(movies);
        }
        public IActionResult Details(int id)
        {
            Movie movie = dbMovieRepository.GetById(id, true, true);
            return View(movie);
        }
        public IActionResult Create()
        {
            FormMovie formMovie = new FormMovie();
            formMovie.Categories = dbCategoryRepository.GetAll();
            formMovie.SelectedCategories = new List<int>();
            formMovie.Actors = dbActorRepository.GetAll();
            formMovie.SelectedActors = new List<int>();
            return View(formMovie);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(FormMovie formMovie)
        {
            if(!ModelState.IsValid)
            {
                formMovie.Actors = dbActorRepository.GetAll();
                formMovie.Categories = dbCategoryRepository.GetAll();
                if (formMovie.SelectedCategories == null)
                {
                    formMovie.SelectedCategories = new List<int>();
                }
                if (formMovie.SelectedActors == null)
                {
                    formMovie.SelectedActors = new List<int>();
                }
                return View(formMovie);
            }
            dbMovieRepository.Create(formMovie);
            Movie createdMovie = dbMovieRepository.GetLast(false, false);
            return RedirectToAction("Details", new { id = createdMovie.Id });
        }
        public IActionResult Update(int id)
        {
            FormMovie formMovie = new FormMovie();
            formMovie.Movie = dbMovieRepository.GetById(id, true, true);
            if (formMovie.Movie == null)
            {
                return NotFound();
            }
            formMovie.Categories = dbCategoryRepository.GetAll();
            formMovie.Actors = dbActorRepository.GetAll();
            formMovie.SelectedCategories = new List<int>();
            formMovie.SelectedActors = new List<int>();
            if(formMovie.Movie.Categories.Count() > 0)
            {
                foreach (Category category in formMovie.Movie.Categories)
                {
                    formMovie.SelectedCategories.Add(category.Id);
                }
            }
            if (formMovie.Movie.Actors.Count() > 0)
            {
                foreach (Actor actor in formMovie.Movie.Actors)
                {
                    formMovie.SelectedActors.Add(actor.Id);
                }
            }
            return View(formMovie);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, FormMovie formMovie)
        {
            Movie movieToUpdate = dbMovieRepository.GetById(id, true, true);
            if (movieToUpdate == null)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                formMovie.Movie = movieToUpdate;
                formMovie.Actors = dbActorRepository.GetAll();
                formMovie.Categories = dbCategoryRepository.GetAll();
                if (formMovie.SelectedCategories == null)
                {
                    formMovie.SelectedCategories = new List<int>();
                }
                if (formMovie.SelectedActors == null)
                {
                    formMovie.SelectedActors = new List<int>();
                }
                return View(formMovie);
            }
            dbMovieRepository.Update(movieToUpdate, formMovie);
            return RedirectToAction("Details", new { id = movieToUpdate.Id });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            Movie movieToDelete = dbMovieRepository.GetById(id, false, false);
            if (movieToDelete == null)
            {
                return NotFound();
            }
            dbMovieRepository.Delete(movieToDelete);
            return RedirectToAction("Index");
        }
    }
}

Controllers/TvShowController.cs
using csharp_boolflix.Data.FormModels;
using csharp_boolflix.Models.Repositories;
using csharp_boolflix.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace csharp_boolflix.Controllers
{
    [Authorize]
    public class TvShowController : Controller
    {
        DbTvShowRepository dbTvShowRepository;
        DbSeasonRepository dbSeasonRepository;
        DbEpisodeRepository dbEpisodeRepository;
        DbCategoryRepository dbCategoryRepository;
        DbActorRepository dbActorRepository;
        public TvShowController(DbTvShowRepository _dbTvShowRepository, DbSeasonRepository _dbSeasonRepository, DbEpisodeRepository _dbEpisodeRepository, DbCategoryRepository _dbCategoryRepository, DbActorRepository _dbActorRepository)
        {
            dbTvShowRepository = _dbTvShowRepository;
            dbSeasonRepository = _dbSeasonRepository;
            dbEpisodeRepository = _dbEpisodeRepository;
            dbCategoryRepository = _dbCategoryRepository;
            dbActorRepository = _dbActorRepository;
        }
        public IActionResult Index()
        {
            List<TvShow> tvShows = dbTvShowRepository.GetAll(false, false);
            return View(tvShows);
        }
        public IActionResult Details(int id)
        {
            TvShow tvShow = dbTvShowRepository.GetById(id, true, true, true);
            foreach(Season season in tvShow.Seasons)
            {
                season.Episodes = dbEpisodeRepository.GetAll(season.Id, false);
            }
            return View(tvShow);
        }
        public IActionResult Create()
        {
            FormTvShow formTvShow = new ();
            formTvShow.Categories = dbCategoryRepository.GetAll();
            formTvShow.SelectedCategories = new List<int>();
            formTvShow.Actors = dbActorRepository.GetAll();
            formTvShow.SelectedActors = new List<int>();
            return View(formTvShow);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(FormTvShow formTvShow)
        {
            if (!ModelState.IsValid)
            {
                formTvShow.Actors = dbActorRepository.GetAll();
                formTvShow.Categories = dbCategoryRepository.GetAll();
                if (formTvShow.SelectedCategories == null)
                {
                    formTvShow.SelectedCategories = new List<int>();
                }
                if (formTvShow.SelectedActors == null)
                {
                    formTvShow.SelectedActors = new List<int>();
                }
                return View(formTvShow);
            }
            dbTvShowRepository.Create(formTvShow);
            TvShow createdTvShow = dbTvShowRepository.GetLast(false, false);
            return RedirectToAction("Details", new { id = createdTvShow.Id });
        }
        public IActionResult Update(int id)
        {
            FormTvShow formTvShow = new FormTvShow();
            formTvShow.TvShow = dbTvShowRepository.GetById(id, true, true, false);
            if (formTvShow.TvShow == null)
            {
                return NotFound();
            }
            formTvShow.Categories = dbCategoryRepository.GetAll();
            formTvShow.Actors = dbActorRepository.GetAll();
            formTvShow.SelectedCategories = new List<int>();
            formTvShow.SelectedActors = new List<int>();
            if (formTvShow.TvShow.Categories.Count() > 0)
            {
                foreach (Category category in formTvShow.TvShow.Categories)
                {
                    formTvShow.SelectedCategories.Add(category.Id);
                }
            }
            if (formTvShow.TvShow.Actors.Count() > 0)
            {
                foreach (Actor actor in formTvShow.TvShow.Actors)
                {
                    formTvShow.SelectedActors.Add(actor.Id);
                }
            }
            return View(formTvShow);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, FormTvShow formTvShow)
        {
            TvShow tvShowToUpdate = dbTvShowRepository.GetById(id, true, true, true);
            if (tvShowToUpdate == null)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                formTvShow.TvShow = tvShowToUpdate;
                formTvShow.Actors = dbActorRepository.GetAll();
                formTvShow.Categories = dbCategoryRepository.GetAll();
                if (formTvShow.SelectedCategories == null)
                {
                    formTvShow.SelectedCategories = new List<int>();
                }
                if (formTvShow.SelectedActors == null)
                {
                    formTvShow.SelectedActors = new List<int>();
                }
                return View(formTvShow);
            }
            dbTvShowRepository.Update(tvShowToUpdate, formTvShow);
            return RedirectToAction("Details", new { id = tvShowToUpdate.Id });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            TvShow tvShowToDelete = dbTvShowRepository.GetById(id, false, false, false);
            if (tvShowToDelete == null)
            {
                return NotFound();
            }
            dbTvShowRepository.Delete(tvShowToDelete);
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_BackOfficeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Boolflix</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/csharp_boolflix.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Boolflix</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Lista Film</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TvShow" asp-action="Index">Lista Serie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Create">Aggiungi Film</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TvShow" asp-action="Create">Aggiungi Serie</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - csharp_boolflix - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_FrontOfficeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Boolflix</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/csharp_boolflix.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Boolflix</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - csharp_boolflix - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Mvc.ViewEngines
@inject IWebHostEnvironment Environment
@inject ICompositeViewEngine Engine
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Boolflix</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/Identity/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/Identity/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
              integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous"
              asp-fallback-href="~/Identity/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/Identity/css/site.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="~/">Boolflix</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @{
                        var result = Engine.FindView(ViewContext, "_LoginPartial", isMainPage: false);
                    }
                    @if (result.Success)
                    {
                        await Html.RenderPartialAsync("_LoginPartial");
                    }
                    else
                    {
                        throw new InvalidOperationException("The default Identity UI layout requires a partial view '_LoginPartial' " +
                        "usually located at '/Pages/_LoginPartial' or at '/Views/Shared/_LoginPartial' to work. Based on your configuration " +
                        $"we have looked at it in the following locations: {System.Environment.NewLine}{string.Join(System.Environment.NewLine, result.SearchedLocations)}.");
                    }
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" optional />
        <main role="main" class="pb-1">
            @RenderBody()
        </main>
    </div>
    <footer class="footer border-top pl-3 text-muted">
        <div class="container">
            &copy; 2022 - la-mia-pizzeria-static
            @{
                var foundPrivacy = Url.Page("/Privacy", new { area = "" });
            }
            @if (foundPrivacy != null)
            {
                <a asp-area="" asp-page="/Privacy">Privacy</a>
            }
        </div>
    </footer>

    <environment include="Development">
        <script src="~/Identity/lib/jquery/dist/jquery.js"></script>
        <script src="~/Identity/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/Identity/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
                asp-fallback-src="~/Identity/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2">
        </script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/Identity/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj">
        </script>
        <script src="~/Identity/js/site.js" asp-append-version="true"></script>
    </environment>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>